<?php
/**
 * -----------------------------------------------------------------------------
 * People — the CRUD console (the "V" in MVC).
 * -----------------------------------------------------------------------------
 * The data table IS the page. Adding, editing and deleting all happen in modal
 * dialogs on THIS page (no separate create/edit pages, no redirects to fill in
 * a form) — exactly the fast, in-place CRUD flow the framework is built for.
 *
 * This view only DISPLAYS data handed to it by the controller ($people). It
 * never queries the database and never validates — those are the Model's and
 * the Validator's jobs.
 *
 * Note how the table headers and every form input are generated by looping over
 * Schema::FIELDS. Rename a column in config/Schema.php and this page follows.
 */

// Recover the state of a failed submission (if any) so the right modal can
// re-open, pre-filled, with the validation messages shown. Read once, then clear.
$submissionErrors = errors();
$hadEditId        = old(Schema::PRIMARY_KEY) !== '';
$editId           = old(Schema::PRIMARY_KEY);
$oldValues        = [];
foreach (Schema::fieldNames() as $field) {
    $oldValues[$field] = old($field);
}
clear_remembered();

$reopen = $submissionErrors ? ($hadEditId ? 'edit' : 'add') : '';
?>

<!-- Page header ------------------------------------------------------------- -->
<div class="mb-8 flex flex-wrap items-end justify-between gap-4">
    <div>
        <p class="font-mono text-xs uppercase tracking-[0.35em] text-sky-400">CRUD demo</p>
        <h1 class="mt-2 font-display text-3xl font-bold tracking-tight text-white">People</h1>
        <p class="mt-1 text-sm text-slate-400">
            <?= count($people) ?> record<?= count($people) === 1 ? '' : 's' ?> in
            <code class="font-mono text-slate-300"><?= e(Schema::TABLE) ?></code>
        </p>
    </div>
    <button type="button" data-open="modal-add"
        class="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-sky-500/20 transition hover:from-sky-400 hover:to-indigo-400">
        <span class="text-lg leading-none">+</span> Add person
    </button>
</div>

<?php if (!$people): ?>
    <!-- Empty state -->
    <div class="rounded-2xl border border-dashed border-edge bg-panel/50 px-6 py-16 text-center">
        <div class="mx-auto mb-4 h-1 w-16 rounded-full bg-gradient-to-r from-sky-500 to-indigo-500"></div>
        <h2 class="font-display text-lg font-semibold text-white">No people yet</h2>
        <p class="mx-auto mt-1 max-w-sm text-sm text-slate-400">Add the first record to see the CRUD flow in action.</p>
        <button type="button" data-open="modal-add"
            class="mt-6 inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500 px-4 py-2.5 text-sm font-semibold text-white transition hover:from-sky-400 hover:to-indigo-400">
            <span class="text-lg leading-none">+</span> Add person
        </button>
    </div>
<?php else: ?>
    <!-- Data table -->
    <div class="overflow-hidden rounded-2xl border border-edge bg-panel">
        <div class="overflow-x-auto">
            <table class="w-full text-left text-sm">
                <thead>
                    <tr class="border-b border-edge text-xs uppercase tracking-widest text-slate-500">
                        <?php foreach (Schema::FIELDS as $field): ?>
                            <th class="px-5 py-3 font-mono font-medium"><?= e($field['label']) ?></th>
                        <?php endforeach; ?>
                        <th class="px-5 py-3 font-mono font-medium">Added</th>
                        <th class="px-5 py-3 text-right font-mono font-medium">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($people as $person): ?>
                        <?php
                        // Only the editable Schema fields, JSON-encoded for the Edit modal.
                        $editable = array_intersect_key($person, array_flip(Schema::fieldNames()));
                        ?>
                        <tr class="border-b border-edge/60 transition last:border-0 hover:bg-white/5">
                            <?php foreach (Schema::fieldNames() as $field): ?>
                                <td class="px-5 py-3 text-slate-200"><?= e($person[$field] ?? '') ?></td>
                            <?php endforeach; ?>
                            <td class="px-5 py-3 font-mono text-xs text-slate-500"><?= e($person['created_at'] ?? '') ?></td>
                            <td class="px-5 py-3">
                                <div class="flex justify-end gap-2">
                                    <button type="button"
                                        class="rounded-md px-2.5 py-1 text-xs font-medium text-sky-400 transition hover:bg-sky-500/10"
                                        data-edit
                                        data-id="<?= (int) $person[Schema::PRIMARY_KEY] ?>"
                                        data-person="<?= e(json_encode($editable)) ?>">Edit</button>
                                    <button type="button"
                                        class="rounded-md px-2.5 py-1 text-xs font-medium text-rose-400 transition hover:bg-rose-500/10"
                                        data-delete
                                        data-id="<?= (int) $person[Schema::PRIMARY_KEY] ?>"
                                        data-label="<?= e(trim(($person['first_name'] ?? '') . ' ' . ($person['last_name'] ?? ''))) ?>">Delete</button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>

<!-- ========================================================================= -->
<!-- Modals. Each is a full-screen overlay hidden until opened by app.js.       -->
<!-- The forms POST to the same routes as before; the controller redirects back.-->
<!-- ========================================================================= -->

<!-- Add ------------------------------------------------------------------- -->
<div id="modal-add" data-modal class="fixed inset-0 z-50 hidden items-center justify-center bg-black/70 p-4">
    <div class="w-full max-w-md rounded-2xl border border-edge bg-panel p-6 shadow-2xl">
        <div class="mb-5 flex items-center justify-between">
            <h2 class="font-display text-lg font-semibold text-white">Add person</h2>
            <button type="button" data-close class="text-slate-500 transition hover:text-slate-200">&times;</button>
        </div>
        <form action="create" method="POST" class="space-y-4" novalidate>
            <?php
            // For a failed "add", re-render the typed values and errors; otherwise blank.
            $values      = $reopen === 'add' ? $oldValues : [];
            $fieldErrors = $reopen === 'add' ? $submissionErrors : [];
            require __DIR__ . '/../partials/fields.php'; // schema-driven inputs
            ?>
            <div class="flex justify-end gap-3 pt-2">
                <button type="button" data-close class="rounded-lg px-4 py-2 text-sm text-slate-400 transition hover:text-slate-200">Cancel</button>
                <button type="submit" class="rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500 px-4 py-2 text-sm font-semibold text-white transition hover:from-sky-400 hover:to-indigo-400">Save person</button>
            </div>
        </form>
    </div>
</div>

<!-- Edit ------------------------------------------------------------------ -->
<div id="modal-edit" data-modal class="fixed inset-0 z-50 hidden items-center justify-center bg-black/70 p-4">
    <div class="w-full max-w-md rounded-2xl border border-edge bg-panel p-6 shadow-2xl">
        <div class="mb-5 flex items-center justify-between">
            <h2 class="font-display text-lg font-semibold text-white">Edit person</h2>
            <button type="button" data-close class="text-slate-500 transition hover:text-slate-200">&times;</button>
        </div>
        <!-- action is set to "update?id=…" by app.js when the modal opens. -->
        <form id="form-edit" method="POST" class="space-y-4" novalidate>
            <?php
            // For the Edit modal the field values are normally filled by JS from
            // the row. If a server-side edit failed, we pre-fill from $oldValues.
            $values      = $reopen === 'edit' ? $oldValues : [];
            $fieldErrors = $reopen === 'edit' ? $submissionErrors : [];
            require __DIR__ . '/../partials/fields.php';
            ?>
            <div class="flex justify-end gap-3 pt-2">
                <button type="button" data-close class="rounded-lg px-4 py-2 text-sm text-slate-400 transition hover:text-slate-200">Cancel</button>
                <button type="submit" class="rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500 px-4 py-2 text-sm font-semibold text-white transition hover:from-sky-400 hover:to-indigo-400">Save changes</button>
            </div>
        </form>
    </div>
</div>

<!-- Delete ---------------------------------------------------------------- -->
<div id="modal-delete" data-modal class="fixed inset-0 z-50 hidden items-center justify-center bg-black/70 p-4">
    <div class="w-full max-w-md rounded-2xl border border-edge bg-panel p-6 shadow-2xl">
        <h2 class="font-display text-lg font-semibold text-white">Delete person</h2>
        <p class="mt-2 text-sm text-slate-400">
            Delete <span id="delete-label" class="font-medium text-slate-200"></span>? This cannot be undone.
        </p>
        <!-- action is set to "delete?id=…" by app.js when the modal opens. -->
        <form id="form-delete" method="POST" class="mt-6 flex justify-end gap-3">
            <button type="button" data-close class="rounded-lg px-4 py-2 text-sm text-slate-400 transition hover:text-slate-200">Cancel</button>
            <button type="submit" class="rounded-lg bg-rose-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-rose-400">Delete</button>
        </form>
    </div>
</div>

<script>
    // If a submission failed validation, tell app.js which modal to re-open.
    window.__reopen = {
        mode: <?= json_encode($reopen) ?>,
        id:   <?= json_encode($hadEditId ? $editId : '') ?>,
    };
</script>
